"""Константы для моделей."""

TAG_FIELDS_MAX_LENGTH = 32
STR_REPR_MAX_LENGTH = 50
SHORT_LINK_MAX_LENGTH = 8
RECIPE_NAME_MAX_LENGTH = 256
COOKING_TIME_MIN = 1
COOKING_TIME_MAX = 32000
INGREDIENT_NAME_MAX_LENGTH = 128
INGREDIENT_UNIT_MAX_LENGTH = 64
INGREDIENT_AMOUNT_MIN = 1
INGREDIENT_AMOUNT_MAX = 32000
