version: '3.3'

volumes:
  pg_data:
  backend_static:
  media:
  frontend_static:

services:

  db:
    container_name: foodgram-db
    image: postgres:13.0-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram-backend
    image: alanbong/foodgram_backend
    env_file: .env
    volumes:
      - backend_static:/app/backend_static/
      - media:/app/backend_media/
    depends_on:
      - db

  frontend:
    container_name: foodgram-front
    image: alanbong/foodgram_frontend
    volumes:
      - frontend_static:/app/result_build/build

  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    depends_on:
      - backend
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_static:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - media:/app/gateway_media
      - backend_static:/gateway_static

